printWidth: 120
singleQuote: true
jsxSingleQuote: true
trailingComma: none
tabWidth: 2
semi: false

plugins:
  - 'prettier-plugin-tailwindcss'

overrides:
  - files:
      - '*.css'
      - '*.scss'
    options:
      singleQuote: false
